### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ndebrabander** [nikitakit/hydrogen-python#20]
[Enter steps to reproduce:]

1. Connect to remote kernel
2. Try to execute any line in a .py file

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [hydrogen-python](https://github.com/nikitakit/hydrogen-python) package 0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/n.debrabander/.atom/packages/hydrogen-python/lib/main.js:108

TypeError: Cannot read property '0' of undefined
    at isBreakpoint (/packages/hydrogen-python/lib/main.js:108:42)
    at expandCode (/packages/hydrogen-python/lib/main.js:126:41)
    at PythonKernelMod.execute (/packages/hydrogen-python/lib/main.js:179:14)
    at MiddlewareAdapter.execute (/packages/Hydrogen/lib/kernel.js:149:24)
    at Kernel.execute (/packages/Hydrogen/lib/kernel.js:288:33)
    at Object._createResultBubble (/packages/Hydrogen/lib/main.js:391:12)
    at Object.createResultBubble (/packages/Hydrogen/lib/main.js:351:12)
    at Object.run (/packages/Hydrogen/lib/main.js:447:12)
    at HTMLElement.hydrogenRunAndMoveDown (/packages/Hydrogen/lib/main.js:108:50)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227580)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1223714)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -4:27.5.0 hydrogen:connect-to-remote-kernel (input.hidden-input)
  3x -4:26.5.0 core:confirm (input.hidden-input)
     -4:10.4.0 hydrogen:connect-to-remote-kernel (input.hidden-input)
  3x -4:09.6.0 core:confirm (input.hidden-input)
     -4:04.7.0 core:move-down (input.hidden-input)
     -4:04.5.0 core:confirm (input.hidden-input)
     -3:52 core:select-to-top (input.hidden-input)
  2x -3:51.2.0 hydrogen:run-and-move-down (input.hidden-input)
     -2:06.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -1:35 hydrogen:run-and-move-down (input.hidden-input)
     -1:19.1.0 settings-view:open (input.hidden-input)
     -0:33.8.0 hydrogen:toggle-inspector (input.hidden-input)
     -0:29.7.0 hydrogen:connect-to-remote-kernel (input.hidden-input)
  3x -0:28 core:confirm (input.hidden-input)
  3x -0:20.8.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:00.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
Hydrogen 2.6.0 
hydrogen-python 0.0.7 
language-terraform 0.8.1 
quick-query 0.15.0 
```

**Comment by ctr26** [comment]
Having this problem on Catalina on Atom Beta when trying to run any code lines Extend code executable

Atom: 1.42.0-beta0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node: v10.11.0
```

TypeError: Cannot read property '0' of undefined
    at isBreakpoint (/Users/ctr26/.atom/packages/hydrogen-python/lib/main.js:108:42)
    at expandCode (/Users/ctr26/.atom/packages/hydrogen-python/lib/main.js:126:41)
    at PythonKernelMod.execute (/Users/ctr26/.atom/packages/hydrogen-python/lib/main.js:179:14)
    at MiddlewareAdapter.execute (/Users/ctr26/.atom/packages/Hydrogen/lib/kernel.js:150:24)
    at Kernel.execute (/Users/ctr26/.atom/packages/Hydrogen/lib/kernel.js:309:33)
    at /Users/ctr26/.atom/packages/Hydrogen/lib/result.js:65:16
    at Object.createResult (/Users/ctr26/.atom/packages/Hydrogen/lib/result.js:74:2)
    at /Users/ctr26/.atom/packages/Hydrogen/lib/main.js:338:14
    at /Users/ctr26/.atom/packages/Hydrogen/lib/main.js:569:30
    at /Users/ctr26/.atom/packages/Hydrogen/lib/kernel-manager.js:84:22
    at /Users/ctr26/.atom/packages/Hydrogen/lib/zmq-kernel.js:59:26
    at ZMQKernel.onConnect (/Users/ctr26/.atom/packages/Hydrogen/lib/zmq-kernel.js:127:21)
    at Socket.emit (events.js:182:13)
    at Object.self._zmq.onMonitorEvent (/Users/ctr26/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:552:12)
```

**Comment by faruqsandi** [comment]
I have this problem too! Do you guys still experience this problem in 2021? @ndebrabander @ctr26

**Comment by ctr26** [comment]
Moved to vscode these days

**Comment by guyujun** [comment]
same this problem in 2021!

**Comment by aydindemircioglu** [comment]
just in case anyone lands here:
it might help to turn off "Extend Executable Code" in the preferences.
(found it somewhere else, had a hard time finding it)

**Comment by aydindemircioglu** [comment]
just in case anyone lands here:
it might help to turn off "Extend Executable Code" in the preferences.
(found it somewhere else, had a hard time finding it)
