### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by cantonio7** [nikitakit/hydrogen-python#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [hydrogen-python](https://github.com/nikitakit/hydrogen-python) package 0.0.8

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/edouardcachoux/.atom/packages/hydrogen-python/lib/main.js:108

TypeError: Cannot read property '1' of undefined
    at isBreakpoint (/packages/hydrogen-python/lib/main.js:108:42)
    at expandCode (/packages/hydrogen-python/lib/main.js:126:41)
    at PythonKernelMod.execute (/packages/hydrogen-python/lib/main.js:179:14)
    at MiddlewareAdapter.execute (/packages/Hydrogen/lib/kernel.js:150:24)
    at Kernel.execute (/packages/Hydrogen/lib/kernel.js:309:33)
    at /packages/Hydrogen/lib/result.js:65:16
    at Object.createResult (/packages/Hydrogen/lib/result.js:74:2)
    at /packages/Hydrogen/lib/main.js:341:14
    at /packages/Hydrogen/lib/main.js:564:7
    at Object.checkForKernel (/packages/Hydrogen/lib/main.js:574:4)
    at Object.run (/packages/Hydrogen/lib/main.js:340:10)
    at HTMLElement.hydrogenRun (/packages/Hydrogen/lib/main.js:103:36)
    at CommandRegistry.handleCommandEvent (/private/var/folders/r9/g3xmlxd112b7t_5x2q01zws00000gn/T/AppTranslocation/ECFE0096-8073-4707-9CCF-64F11B61BB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:349538)
    at KeymapManager.dispatchCommandEvent (/private/var/folders/r9/g3xmlxd112b7t_5x2q01zws00000gn/T/AppTranslocation/ECFE0096-8073-4707-9CCF-64F11B61BB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1256534)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/r9/g3xmlxd112b7t_5x2q01zws00000gn/T/AppTranslocation/ECFE0096-8073-4707-9CCF-64F11B61BB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1252668)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/r9/g3xmlxd112b7t_5x2q01zws00000gn/T/AppTranslocation/ECFE0096-8073-4707-9CCF-64F11B61BB31/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -0:44.4.0 tabs:close-tab (div.title)
 10x -0:40.3.0 core:backspace (input.hidden-input)
     -0:29.4.0 editor:newline (input.hidden-input)
     -0:25.2.0 core:move-down (input.hidden-input)
     -0:24.9.0 editor:newline (input.hidden-input)
     -0:24 core:move-up (input.hidden-input)
 10x -0:23.7.0 core:move-right (input.hidden-input)
     -0:20.7.0 hydrogen:run (input.hidden-input)
     -0:20.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
atom-python-test 1.0.1 
autocomplete-python 1.16.0 
bootstrap4-snippets 0.2.2 
busy-signal 2.0.1 
city-lights-ui 1.5.3 
file-icons 2.1.41 
file-type-icons 1.3.4 
hey-pane 1.2.0 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
hydrogen-python 0.0.8 
ide-python 1.5.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
ipython-exec 1.2.0 
ipython-run 0.3.1 
isotope-ui 2.8.5 
kite 0.182.0 
linter 2.3.1 
linter-ui-default 1.8.1 
minimap 4.29.9 
platformio-ide-terminal 2.10.0 
python-indent 1.2.6 
python-isort 0.0.7 
python-linters 0.0.4 
script 3.26.0 
scroll-through-time 0.3.1 
seti-ui 1.11.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 4.3.3 
teletype 0.13.4 
tool-bar-shortcuts 0.1.5 
zentabs 0.8.9 
```

**Comment by dlangerm** [comment]
Same issue here

Fixed by disabling "Extend Executable Code"
